# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mido/setup-makefiles.sh
# Added my vendor branch
# Credits to zeelog and erick
LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),mido)

endif
